# Generated by Django 3.2.4 on 2021-06-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
